# Generated by Django 6.0 on 2025-12-27 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('ip_address', 'date')},
            },
        ),
    ]
